#!/bin/bash

# Extract the file name of photo with id 'N'
# Run from the directory with the 'metadata' file

LINE=0
while read line; do
    if [[ $line = \"path* ]]; then
       LINE=$((LINE + 1))
    fi
    if [[ $LINE = $1 ]]; then
     	echo $line
	break
    fi
done < metadata
		      
